<<<<<<< SEARCH
def html_table_to_markdown(html_content: str) -> str:
    """
    Converts standard HTML table markup to Markdown format.
    """
    if not html_content or "<table" not in html_content.lower():
        return html_content

    try:
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(html_content, "html.parser")
        tables = soup.find_all("table")
        if not tables:
            return html_content

        md_tables = []
        for table in tables:
            rows = table.find_all("tr")
            if not rows:
                continue

            grid = []
            max_cols = 0
            for row in rows:
                cells = row.find_all(["th", "td"])
                row_data = [cell.get_text(strip=True).replace("\n", " ") for cell in cells]
                if row_data:
                    grid.append(row_data)
                    max_cols = max(max_cols, len(row_data))

            if not grid:
                continue

            for r in grid:
                while len(r) < max_cols:
                    r.append("")

            md_lines = []
            header = grid[0]
            md_lines.append("| " + " | ".join(header) + " |")
            md_lines.append("| " + " | ".join(["---"] * max_cols) + " |")

            for r in grid[1:]:
                md_lines.append("| " + " | ".join(r) + " |")

            md_tables.append("\n".join(md_lines))

        return "\n\n".join(md_tables)
    except Exception:
        return html_content
=======
def html_table_to_markdown(html_content: str) -> str:
    """
    Converts standard HTML table markup to Markdown format with delimiter escaping and span support.
    """
    if not html_content or "<table" not in html_content.lower():
        return html_content

    try:
        from bs4 import BeautifulSoup
        # Ensure unclosed HTML generated by sequence truncation is safely wrapped
        fixed_html = html_content
        if "</table>" not in fixed_html.lower():
            fixed_html += "</table>"
        if "</body>" not in fixed_html.lower():
            fixed_html += "</body></html>"

        soup = BeautifulSoup(fixed_html, "html.parser")
        tables = soup.find_all("table")
        if not tables:
            return html_content

        md_tables = []
        for table in tables:
            rows = table.find_all("tr")
            if not rows:
                continue

            grid = []
            max_cols = 0
            for row in rows:
                cells = row.find_all(["th", "td"])
                row_data = []
                for cell in cells:
                    text = cell.get_text(separator=" ", strip=True).replace("\n", " ")
                    text = text.replace("|", "\\|")
                    colspan = 1
                    if cell.has_attr("colspan"):
                        try:
                            colspan = max(1, int(cell["colspan"]))
                        except ValueError:
                            colspan = 1
                    row_data.append(text)
                    for _ in range(colspan - 1):
                        row_data.append("")

                if row_data:
                    grid.append(row_data)
                    max_cols = max(max_cols, len(row_data))

            if not grid or max_cols == 0:
                continue

            for r in grid:
                while len(r) < max_cols:
                    r.append("")

            md_lines = []
            header = grid[0]
            md_lines.append("| " + " | ".join(header) + " |")
            md_lines.append("| " + " | ".join(["---"] * max_cols) + " |")

            for r in grid[1:]:
                md_lines.append("| " + " | ".join(r) + " |")

            md_tables.append("\n".join(md_lines))

        return "\n\n".join(md_tables)
    except Exception:
        return html_content
>>>>>>> REPLACE
